wip

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -55,9 +55,11 @@ jobs:
         uses: actions/checkout@v6.0.0
 
       - name: Setup Xcode
-        uses: maxim-lobanov/setup-xcode@v1
-        with:
-          xcode-version: latest-stable
+        shell: bash
+        run: |
+          sudo xcode-select -s /Applications/Xcode_26.0.app/Contents/Developer
+          [[ "$(xcodebuild -version)" == *"Xcode 26.0.1"* ]] || { echo "Failed to set Xcode version"; exit 1; }
+          echo "Xcode version 26.0.1 is set successfully."
 
       - name: Setup Node.js
         uses: actions/setup-node@v6.0.0
